### ISSUE TITLE
Not good

### ISSUE THREAD

**Issue by nokonoko** [Seqi/seqi#1]
Please write more buddy

**Comment by Seqi** [comment]
I got more text than you =(

**Comment by nokonoko** [comment]
T̘̘̭͚͍̩͔h̹̦̘̲̯̭̙͚̯i̧̠͠͞s̨̲͚̪ͅ ̧̯̣͚̟̳̜̼̻͔̀i̫̠̠s͏̠̥ ̨̭̭͙̹̝͇͔͢ņ̪̻̬̱̫̩͚͇o̵̙͜͝ͅț̷̼͍̝͙͈̺̜ ̧̤̳͎̠͈̥̯͘͝a̴͙̻̬̳͈̝͡b̷͏̵̤̰̼̤ǫ̬ú͇̪̥̦͟͝t̪͚̜͍̳́ ͚̥͈̪̮̗̯̙m̼͖̤͍̺͇͡͝e̶͇̲͓̘̝̝̱͇͍͡ ̻̜̼̘̙̰͞t̡̲̙̭͜͞h̺͍i̛͔̖̬̰͖͓͜ͅs̲̲̠ ͈̪̱̫́͝i̡̛̜̤͍̭͇͍͉ṣ̜̝̥̺ͅ ̣̦͔̭̕a͚̠̻̠b̛̦͈̩́o̶̫͇͙̙u̷̷̜̮͞ͅͅt̪̜̗͕͙̭̬̙ͅ ̱͈ͅy̛̝̜̦͙͓̯̗͜ơ̲͉͘u̧̘͓̖͢͡ ͕̣͙̤̙̦̀Y̗͉̝O̞̗͓̘̪ͅU̸̷̱͔̘̠͈̼̺ ̗̥̙Ń̢̧̠̯͕̣͍͉͔̭E͖̳͖̻͓̲E̸̶̮͙̳̖ͅD̸̡͚͍̤̻ ̞̻͓̱̳̬͓Ṯ̷̼O̵͖̠̯͇͜ ̥̠̦̀̕W̝̹̫̝̕͜ͅR̵҉̡̖̻̟͈ͅI̠̼͞ͅT͢҉̰̳̫̦̱̱͔̭E҉̰͔̟̠͡ ̗̝̣̲̘̟͕͞ͅM̙͚̖̹͓̤̳̺̜͠Ọ̞͇̯͙͉̖̺͜R͇̬̥̳̫͚͜͠E̶͙̤̬̬̟͚͟ ̛̮̮̪͔̦̕ͅÁ̞̤̫̘̫͈̩̼ͅB͠҉͉̟̙͙Ơ͈͈͕̭̜̩͞Ų̷̥͇̦̮̖̪̻T҉̩̤̮̳̲ ̶̺̀͢U͏͓͕̫̩͓̖R̵͏̩̯͓͇̗͉Ş͙̰̲͓̘͜͠È̟̳̻͇͜Ḻ̨͇͕͕̯̩F̲͍̲̥͙̫́͟

**Comment by Seqi** [comment]
give me some ideas!!!

**Comment by nokonoko** [comment]
that's better 🥇

**Comment by Seqi** [comment]
thank u leave a like and a subscribe!
